### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by remimimimi** [blainehansen/magma#4]
Recently I found your project and was very surprised how clearly it describes the ideas that I recently came up with about my programming language. Therefore, I really want to discuss the project with you and take part in its development. I sent you an email with links to my accounts.

**Comment by blainehansen** [comment]
Responded to your email :)

**Comment by zyansheep** [comment]
I would also like to discuss magmide and whether or not we can exchange ideas. (I am also working on a dependently-typed bare-metal language). I have emailed you a link with my matrix account.
